version: '3.8'

services:
  ngo_postgres:
    image: postgres:15-alpine
    container_name: ngo_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ngo_db
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ngo_postgres_data:/var/lib/postgresql/data
    networks:
      - ngo_network

volumes:
  ngo_postgres_data:

networks:
  ngo_network:
    driver: bridge
